pipeline {
    agent {
        label 'docker-agent'
    }

    stages {
        stage('Run code coverage test') {
            when {
                branch 'main'
            }
            steps {
                sh '''
                cd Chapter08/sample1
                ./gradlew test jacocoTestReport jacocoTestCoverageVerification --continue
                '''
            }
        }

        stage('Run unit test and checkstyle') {
            when {
                not { branch 'main' }
            }

            steps {
                echo 'Run unit tests and checkstyle'
                sh '''
                cd Chapter08/sample1
                ./gradlew test jacocoTestReport checkstyleMain --continue
                '''
            }
        }
    }

    post {
        always {
            publishHTML(
                    target: [
                        reportDir: 'Chapter08/sample1/build/reports/jacoco/test/html',
                        reportFiles: 'index.html',
                        reportName: 'JaCoCo Report'
                    ]
                )
        }

        failure {
            echo 'tests fail!'
        }

        success {
            echo 'tests pass!'
        }
    }
}
