pipeline {
    agent {
        label 'docker-agent'
    }
    
    stages {
        stage('Run code coverage test') {
            when {
                branch 'main'
            }
            steps {
                sh """
                cd Chapter08/sample1
                ./gradlew test jacocoTestCoverageVerification jacocoTestReport
                """

                publishHTML(
                    target: [
                        reportDir: 'Chapter08/sample1/build/reports/jacoco/test/html',
                        reportFiles: 'index.html',
                        reportName: "JaCoCo Code Coverage Report"
                    ]
                )
            }
        }

        stage('Run unit test and checkstyle') {
            when {
                branch '*feature*'
            }
            steps {
                echo "Run unit test and checkstyle"
                sh """
                cd Chapter08/sample1
				./gradlew test checkstyleMain
                """

                publishHTML(
                    target: [
                        reportDir: 'Chapter08/sample1/build/reports/tests/test',
                        reportFiles: 'index.html',
                        reportName: "Test Report"
                    ]
                )

                publishHTML(
                    target: [
                        reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                        reportFiles: 'main.html',
                        reportName: "JaCoCo Checkstyle"
                    ]
                )
            }
        }  

        stage('Invalid branch') {
            when {
                not {
                    anyOf {
                        branch 'main'
                        branch '*feature*'
                    }
                }
            }
            steps {
                error "ERROR!!! ${env.BRANCH_NAME} is not a valid branch!"
            }
        }
    }

    post {
        failure {
            echo 'pipeline failure'
        }
        success {
            echo 'pipeline ran perfectly'
        }
    }
}